services:
  simcore:
    build:
      context: .
      dockerfile: traffic_simulation/simCore.Dockerfile
    container_name: simcore
    volumes:
      - ./config/config.json:/app/traffic_simulation/core/config.json
    networks:
      - simnet
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  agentmodule:
    build:
      context: .
      dockerfile: traffic_simulation/agentModule.Dockerfile
    container_name: agentmodule
    volumes:
      - ./config/config.json:/app/traffic_simulation/core/config.json
    networks:
      - simnet
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  trafficmodule:
    build:
      context: .
      dockerfile: traffic_simulation/trafficModule.Dockerfile
    container_name: trafficmodule
    volumes:
      - ./config/config.json:/app/traffic_simulation/core/config.json
    networks:
      - simnet
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  vizmodule:
    build:
      context: .
      dockerfile: traffic_simulation/vizModule.Dockerfile
    container_name: vizmodule
    ports:
      - "8050:8050"
    volumes:
      - ./config/config.json:/app/traffic_simulation/core/config.json
    networks:
      - simnet
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

networks:
  simnet:
    driver: bridge
